apiVersion: apps/v1
kind: Deployment
metadata:
  name: dreyfus-pod-deployment
  labels:
    podname: dreyfus-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      podname: dreyfus-pod
  template:
    metadata:
      labels:
        podname: dreyfus-pod
    spec:
      containers:
      - name: motd
        image: shinigami5253/motd-api:v1
        env:
          - name: APP_PORT
            value: "80"
          - name: MESSAGE
            value: "Bonjour, bienvenue sur notre service MOTD!"