---
apiVersion: v1
kind: Pod
metadata:
  name: dreyfus-pod
  labels:
    podname: dreyfus-pod
    app: motd
spec:
  containers:
  - name: motd
    image: shinigami5253/motd-api:v1
    env:
    - name: APP_PORT
      value: "80"
    - name: MESSAGE
      value: "Bonjour, bienvenue sur notre service MOTD!"
    