---
apiVersion: v1
kind: Pod
metadata:
  name: dreyfus-pod
  labels:
    app: motd
spec:
  containers:
  - name: motd
    image: shinigami5253/motd-api:v1 
    env:
    -name: APP_PORT
    value: "80"
    