apiVersion: v1
kind: Service
metadata:
  name: dreyfus-service
spec:
  selector:
    app.kubernetes.io/name: dreyfus-pod
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 80
  type: ClusterIP